[package]
name = "mc-idle"
version = "0.1.0"
edition = "2018"

[dependencies]
bytes = "1.1"
futures = "0.3"
minecraft-protocol = { git = "https://github.com/timvisee/minecraft-protocol", rev = "c578492" }
tokio = { version = "1", features = ["full"] }
