# lazymc configuration

[public]
# Public address. IP and port users connect to.
# Shows sleeping status, starts server on connect, and proxies to server.
address = "0.0.0.0:25565"

[server]
# Server directory.
directory = "."

# Command to start the server.
# Warning: if using a bash script read: https://github.com/timvisee/lazymc/blob/master/docs/command_bash.md
command = "java -Xmx1G -Xms1G -jar server.jar --nogui"

# Server address. Internal IP and port of server started by lazymc to proxy to.
address = "127.0.0.1:25566"

# Immediately wake server when starting lazymc.
wake_on_start = false

[time]
# Sleep after number of seconds.
sleep_after = 60

# Minimum time in seconds to stay online when server is started.
minimum_online_time = 60

[messages]
# MOTD when server is sleeping.
motd_sleeping = "☠ Server is sleeping\n§2☻ Join to start it up"

# MOTD when server is starting.
motd_starting = "§2☻ Server is starting...\n§7⌛ Please wait..."

# MOTD when server is stopping.
motd_stopping = "☠ Server going to sleep...\n⌛ Please wait..."

# Login (kick) message when server is starting.
login_starting = "Server is starting... §c♥§r\n\nThis may take some time.\n\nPlease try to reconnect in a minute."

# Login (kick) message when server is stopping.
login_stopping = "Server is going to sleep... §7☠§r\n\nPlease try to reconnect in a minute to wake it again."

[rcon]
# Enable sleeping server through RCON.
# Must be enabled on Windows.
enabled = true

# Server RCON port. Must differ from Minecraft server port.
port = 25575

# Server RCON password.
password = ""

# Randomize ingress server RCON password on each start.
randomize_password = true

[advanced]
# Automatically update values in Minecraft server.properties file as required.
rewrite_server_properties = true
