# lazymc configuration
#
# You must configure your server directory and start command, see:
# - server.directory
# - server.command
#
# All defaults are commented out, change it if you desire.
# You can probably leave the rest as-is.
#
# You may generate a new configuration with: lazymc config generate
# Or find the latest at: https://is.gd/WWBIQu

[public]
# Public address. IP and port users connect to.
# Shows sleeping status, starts server on connect, and proxies to server.
#address = "0.0.0.0:25565"

# Server version & protocol hint.
# Sent to clients until actual server version is known.
# See: https://is.gd/FTQKTP
#version = "1.17.1"
#protocol = 756

[server]
# Server address. Internal IP and port of server started by lazymc to proxy to.
# Port must be different from public port.
#address = "127.0.0.1:25566"

# Server directory, defaults to current directory.
directory = "."

# Command to start the server.
# Warning: if using a bash script read: https://is.gd/k8SQYv
command = "java -Xmx1G -Xms1G -jar server.jar --nogui"

# Immediately wake server when starting lazymc.
#wake_on_start = false

# Immediately wake server after crash.
#wake_on_crash = false

[time]
# Sleep after number of seconds.
#sleep_after = 60

# Minimum time in seconds to stay online when server is started.
#minimum_online_time = 60

# Hold client for number of seconds on connect while server starts.
# 0 to disable and disconnect immediately, keep below Minecraft timeout of 30 seconds.
#hold_client_for = 25

# Server start/stop timeout in seconds. Force kill server process if it takes too long.
#start_timeout = 300
#stop_timeout = 150

[messages]
# MOTDs, shown in server browser.
#motd_sleeping = "☠ Server is sleeping\n§2☻ Join to start it up"
#motd_starting = "§2☻ Server is starting...\n§7⌛ Please wait..."
#motd_stopping = "☠ Server going to sleep...\n⌛ Please wait..."

# Login messages, when user tries to connect.
#login_starting = "Server is starting... §c♥§r\n\nThis may take some time.\n\nPlease try to reconnect in a minute."
#login_stopping = "Server is going to sleep... §7☠§r\n\nPlease try to reconnect in a minute to wake it again."

[rcon]
# Enable sleeping server through RCON.
# Must be enabled on Windows.
#enabled = true

# Server RCON port. Must differ from public and server port.
#port = 25575

# Server RCON password.
# Or whether to randomize password each start (recommended).
#password = ""
#randomize_password = true

[advanced]
# Automatically update values in Minecraft server.properties file as required.
#rewrite_server_properties = true
