# lazymc configuration

[public]
# Egress address.
#
# Public IP and port users will connect to.
# Shows sleeping status, starts server on connect, and proxies to ingress server.
address = "0.0.0.0:25565"

[server]
# Server directory.
directory = "."

# Command to start the server.
#
# Warning: if using a bash script, see: https://github.com/timvisee/lazymc/blob/master/docs/command_bash.md
command = "java -Xmx1G -Xms1G -jar server.jar --nogui"

# Ingress address.
#
# Internal IP and port of server started by lazymc to proxy to.
address = "127.0.0.1:25566"

# Immediately wake server when starting lazymc.
wake_on_start = false

[time]
# Sleep after number of seconds.
sleep_after = 60

# Minimum time in seconds to stay online when server is started.
minimum_online_time = 60

[messages]
# MOTD when server is sleeping.
motd_sleeping = "☠ Server is sleeping\n§2☻ Join to start it up"

# MOTD when server is starting.
motd_starting = "§2☻ Server is starting...\n§7⌛ Please wait..."

# Login (kick) message when server is starting.
login_starting = "Server is starting... §c♥§r\n\nThis may take some time.\n\nPlease try to reconnect in a minute."

[advanced]
# Automatically set IP and port in Minecraft server.properties file.
rewrite_server_properties = true
